/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-purple-600',
    'text-white',
    'shadow-lg',
    'bg-black/40',
    'text-purple-200',
    'border',
    'border-purple-700',
    'rounded-full',
    'font-semibold',
    'text-lg',
    'flex',
    'items-center',
    'gap-4',
    'justify-center',
    'transition-all',
    'duration-200',
    'w-[320px]',
    'px-8',
    'py-3',
    'w-[420px]',
    'rounded-2xl',
    'rounded-full',
    'border',
    'border-purple-400',
    'bg-[rgba(36,38,62,0.55)]',
    'bg-[rgba(80,60,120,0.65)]',
    'text-white',
    'placeholder-[#e0cfff]',
    'text-lg',
    'font-medium',
    'font-bold',
    'text-center',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-purple-400',
    'transition-all',
    'shadow-md',
    'shadow-xl',
    'hover:bg-[rgba(80,60,120,0.65)]',
    'hover:shadow-lg',
    'hover:scale-105',
    'ring-2',
    'ring-purple-400',
    'scale-105',
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
